export const LOADING_INIT = 'LOADING_INIT';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const TOGGLE_MENU_STATE = 'TOGGLE_MENU_STATE';
export const TOGGLE_MENU_HIDE_STATE = 'TOGGLE_MENU_HIDE_STATE';

export const CHANGE_CLIENT_CURRENT_STEP = 'CHANGE_CLIENT_CURRENT_STEP';
export const CHANGE_INVESTOR_CURRENT_STEP = 'CHANGE_INVESTOR_CURRENT_STEP';
export const COMPLETE_CLIENT_STEP_ONE = 'COMPLETE_CLIENT_STEP_ONE';
export const COMPLETE_INVESTOR_STEP_ONE = 'COMPLETE_INVESTOR_STEP_ONE';
export const COMPLETE_CLIENT_STEP_TWO = 'COMPLETE_CLIENT_STEP_TWO';
export const COMPLETE_INVESTOR_STEP_TWO = 'COMPLETE_INVESTOR_STEP_TWO';
export const COMPLETE_CLIENT_STEP_THREE = 'COMPLETE_CLIENT_STEP_THREE';
export const INVESTOR_CHANGE_CURRENT_STEP = 'INVESTOR_CHANGE_CURRENT_STEP';

export const SET_CLIENT_INFORMATION = 'SET_CLIENT_INFORMATION';
export const STEP_CLIENT_DISABLED = 'STEP_CLIENT_DISABLED';
export const SET_INVESTOR_INFORMATION = 'SET_INVESTOR_INFORMATION';
export const STEP_INVESTOR_DISABLED = 'STEP_INVESTOR_DISABLED';

export const CLEAR_RECAPTCHA = 'CLEAR_RECAPTCHA';
export const SET_RECAPTCHA = 'SET_RECAPTCHA';

export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
