export const LOADING_INIT = 'LOADING_INIT';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const TOGGLE_MENU_STATE = 'TOGGLE_MENU_STATE';

export const CLIENT_CHANGE_CURRENT_STEP = 'CLIENT_CHANGE_CURRENT_STEP';
export const INVESTOR_CHANGE_CURRENT_STEP = 'INVESTOR_CHANGE_CURRENT_STEP';
